---
- name: Install Operator SDK system dependencies
  dnf:
    name: [
            ansible,
            ansible-lint,
            docker,
            kubernetes,
            kubernetes-client,
            python-flake8,
            python-molecule,
            python-molecule-docker,
            python-openshift
          ]
    state: present

- name: Install Python dependencies
  pip:
    name: 
      - kubernetes < 12.0.0

- name: Create docker group
  group:
    name: docker
    state: present
  become: yes

- name: Ensure user is added to docker group
  user:
    name: "{{ dev_username }}"
    groups: ['docker']
    append: yes
  become: yes

- name: Reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection

- name: Start docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

# I don't like to do this, but the manually installed minikube needs to many SELinux changes
- name: Set SELinux to permissive
  selinux:
    policy: targeted
    state: permissive

# Install minikube
- name: Download minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-{{minikube_version}}.x86_64.rpm
    dest: /tmp/

- name: Install minikube
  dnf:
    name: /tmp/minikube-{{minikube_version}}.x86_64.rpm
    state: present
    disable_gpg_check: true

- name: Set minikube default driver to docker
  command: minikube config set vm-driver docker
  become: yes
  become_user: "{{ dev_username }}"

# Install kustomize
- name: Retrieve kustomize
  get_url:
    url: https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh
    dest: /tmp/install_kustomize.sh
  
- name: Create kustomize binary
  command: bash /tmp/install_kustomize.sh {{ kustomize_version }}
  args:
    chdir: /tmp/
    creates: /tmp/kustomize

- name: Move kustomize binary to correct location
  copy:
    src: /tmp/kustomize
    dest: /usr/local/bin/kustomize
    mode: '0755'
    remote_src: yes

# "Install" the operator SDK
- name: Retrieve operator-sdk binary
  get_url:
    url: https://github.com/operator-framework/operator-sdk/releases/download/v{{operator_sdk_version}}/operator-sdk-v{{operator_sdk_version}}-x86_64-linux-gnu
    dest: /tmp/

- name: Move operator-sdk binary to correct location
  copy:
    src: /tmp/operator-sdk-v{{operator_sdk_version}}-x86_64-linux-gnu
    dest: /usr/local/bin/operator-sdk
    mode: '0755'
    remote_src: yes
