apiVersion: v1
kind: Service
metadata:
  name: kerberos
  labels:
    app: kerberos
    service: kerberos
spec:
  ports:
    - name: "kdc" 
      port: 88
      targetPort: 88
      protocol: TCP
    - name: "kadmin"
      port: 749
      targetPort: 749
      protocol: TCP
  selector:
    app: kerberos
