apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mbmbsfrontends.apps.fedoraproject.org
spec:
  group: apps.fedoraproject.org
  names:
    kind: MBMbsFrontend
    listKind: MBMbsFrontendList
    plural: mbmbsfrontends
    singular: mbmbsfrontend
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
