apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mbkojiras.apps.fedoraproject.org
spec:
  group: apps.fedoraproject.org
  names:
    kind: MBKojira
    listKind: MBKojiraList
    plural: mbkojiras
    singular: mbkojira
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
