apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mbkojibuilders.apps.fedoraproject.org
spec:
  group: apps.fedoraproject.org
  names:
    kind: MBKojiBuilder
    listKind: MBKojiBuilderList
    plural: mbkojibuilders
    singular: mbkojibuilder
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
