---
- name: Create.KojiBuilder
  hosts: localhost
  connection: local
  vars:
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    custom_resource: "{{ deploy_dir }}/crds/apps.fedoraproject.org_v1alpha1_mbkojibuilder_cr.yaml"
  tasks:
    - name: Create koji-builder custom resource
      k8s:
        state: present
        namespace: "{{ namespace }}"
        definition: "{{ lookup('file', custom_resource) | from_yaml }}"
        wait: true
        wait_condition:
          reason: Successful
          status: "True"
          type: Running
      delay: 10
      retries: 30
      ignore_errors: true
