---
# defaults file for mbs-backend
mbs_backend_replicas: "{{ replicas | default(1) }}"
mbs_backend_image: "{{ image | default('quay.io/fedora/mbs-backend:latest') }}"
mbs_backend_hub_username: "{{ hub_username | default('mbs') }}"
mbs_backend_cacert_secret: "{{ cacert_secret|default('mbs-ca-cert') }}"
mbs_backend_client_cert_secret: "{{ client_cert_secret|default('mbs-client-cert') }}"

mbs_backend_postgres_secret: "{{ postgres_secret | default('postgres') }}"
mbs_configmap: "{{ configmap | default('mbs-configmap') }}"
mbs_fedora_versions: "{{ fedora_versions | default(['32']) }}"
mbs_hub_host: "{{ hub_host | default('koji-hub:8443') }}"
mbs_messaging_system: "{{ messaging_system | default('fedmsg') }}"
mbs_topic_prefix: "{{ topic_prefix | default('org.fedoraproject.dev') }}"
mbs_scm_url: "{{ scm_url | default('git+https://src.fedoraproject.org/modules/') }}"
mbs_rpms_default_repository: "{{ rpms_default_repository|default('git+https://src.fedoraproject.org/rpms/') }}"
mbs_rpms_default_cache: "{{ rpms_default_cache|default('https://src.fedoraproject.org/repo/pkgs/') }}"
mbs_modules_default_repository: "{{ modules_default_repository|default('git+https://src.fedoraproject.org/modules/') }}"
mbs_pdc_url: "{{ pdc_url|default('https://pdc.stg.fedoraproject.org/rest_api/v1') }}"
mbs_oidc_required_scope: "{{ oidc_required_scope|default('https://mbs.fedoraproject.org/oidc/submit-build') }}"

mbs_backend_shared_pvc: "{{ shared_pvc | default('koji-hub-mnt-pvc') }}"
mbs_backend_mbox: "{{ mbox | default('') }}"
