---
- block:
    - name: retrieve mbox resource
      k8s_info:
        api_version: apps.fedoraproject.org/v1alpha1
        kind: Mbox
        namespace: "{{ meta.namespace }}"
        name: "{{ mbs_backend_mbox }}"
      register: k8s_mboxes
    - fail:
        msg: "Failed to find mbox {{ mbs_backend_mbox }} in namespace {{ meta.namespace }}"
      when: k8s_mboxes.resources|length == 0
  when: mbs_backend_mbox|length > 0

- set_fact:
    mbs_backend_postgres_secret: "{{ k8s_mboxes.resources[0].spec.psql_secret_name }}"
    mbs_configmap: "{{ k8s_mboxes.resources[0].spec.mbs.configmap }}"
  when: mbs_backend_mbox|length > 0

- block:
    - name: Retrieve postgresql secret
      k8s_info:
        api_version: v1
        kind: Secret
        namespace: "{{ meta.namespace }}"
        name: "{{ mbs_backend_postgres_secret }}"
      register: k8s_psql_secrets
    - fail:
        msg: "Secret {{ mbs_backend_postgres_secret }} not found in namespace {{ meta.namespace }}"
      when: k8s_psql_secrets.resources|length == 0
    - set_fact:
        psql_secret: "{{ k8s_psql_secrets.resources[0] }}"

- name: create temporary component directory
  tempfile:
    state: directory
    prefix: mbs
    suffix: backend
  register: mbs_dir

- name: check if mbs-configmap exists
  k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: "{{ meta.namespace }}"
    name: "{{ mbs_configmap }}"
  register: k8s_mbs_cm

- block:
    - name: ensure mbs configmap
      template:
        src: mbs-configmap.yaml.j2
        dest: "{{ mbs_dir.path }}/mbs-configmap.yaml"
      vars:
        mbs_psql_hostname: "{{ psql_secret.data.POSTGRES_HOST | b64decode }}"
        mbs_psql_db_name: "{{ psql_secret.data.POSTGRES_DB | b64decode }}"
        mbs_psql_user: "{{ psql_secret.data.POSTGRES_USER | b64decode }}"
        mbs_psql_pass: "{{ psql_secret.data.POSTGRES_PASSWORD | b64decode }}"
    - k8s:
        state: present
        wait: true
        namespace: "{{ meta.namespace }}"
        src: "{{ mbs_dir.path }}/mbs-configmap.yaml"
  when: k8s_mbs_cm.resources|length == 0

- include_tasks: cert.yml

- block:
    - name: retrieve and set shared pvc name var
      k8s_info:
        api_version: apps.fedoraproject.org/v1alpha1
        kind: Mbox
        namespace: "{{ meta.namespace }}"
        name: "{{ mbs_backend_mbox }}"
      register: k8s_mboxes
    - fail:
        msg: "Failed to find mbox {{ mbs_backend_mbox }} in namespace {{ meta.namespace }}"
      when: k8s_mboxes.resources|length == 0
    - set_fact:
        mbs_backend_shared_pvc: "{{ k8s_mboxes.resources[0].spec.koji_pvc_name }}"
  when: mbs_backend_mbox|length > 0

- block:
    - name: ensure mbs-backend deployment
      template:
        src: deployment.yaml.j2
        dest: "{{ mbs_dir.path }}/deployment.yaml"
    - k8s:
        src: "{{ mbs_dir.path }}/deployment.yaml"
        state: present
        namespace: "{{ meta.namespace }}"
        wait: true

- name: delete temporary component directory
  file:
    path: "{{ mbs_dir.path }}"
    state: absent
