---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: true
    ansible_connection_options: {}
lint: |
  yamllint roles/
platforms:
  - name: test-cluster
    groups:
      - k8s
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        namespace: ${TEST_NAMESPACE:-osdk-test}
        tmpdir: /tmp/mbox
        operator_image: quay.io/lrossett/mbox-operator:latest
  lint:
    name: ansible-lint
    enabled: false
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
scenario:
  name: test-cluster
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - prepare
#    - create
#    - converge
    - side_effect
    - verify
    #- destroy
verifier:
  name: testinfra
  lint: |
    flake8
