---

- name: Install helpful development packages
  dnf:
    name: [
           git,
           vim-enhanced,
           python3-black,
           tmux,
           htop
          ]
    state: present

# Add various helpful configuration files
- name: Copy test configuration
  copy: src=mbbox-dev.yml dest=/home/vagrant/mbbox-dev.yml

- import_tasks: rabbitmq.yml
