---
- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    pull_policy: Never
    REPLACE_IMAGE: apps.fedoraproject.org/mbox-operator:testing
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/apps.fedoraproject.org_v1alpha1_mbkojihub_cr.yaml'])) | from_yaml }}"

  tasks:
    - block:
        - name: Delete postgres resources
          k8s:
            state: absent
            namespace: "{{ namespace }}"
            definition: "{{ lookup('file', deploy_dir + '/../../components/psql/' + item) }}"
            wait: true
          with_items:
            - 0-secret.yaml
            - 1-pvc.yaml
            - 2-deployment.yaml
            - 3-service.yaml

        - name: Delete rabbitmq resources
          k8s:
            state: absent
            namespace: "{{ namespace }}"
            definition: "{{ lookup('file', deploy_dir + '/../../components/rabbitmq/' + item) }}"
            wait: true
          with_items:
            - 0-secret.yaml
            - 1-configmap.yaml
            - 2-pvc.yaml
            - 3-service.yaml
            - 4-deployment.yaml

        - name: Delete the Operator Deployment
          k8s:
            state: absent
            namespace: '{{ namespace }}'
            definition: "{{ lookup('template', '/'.join([deploy_dir, 'operator.yaml.j2'])) }}"
          register: delete_deployment
          when: hostvars[groups.k8s.0].build_cmd.changed

        - name: Wait 30s for Operator Deployment to terminate
          k8s_info:
            api_version: '{{ definition.apiVersion }}'
            kind: '{{ definition.kind }}'
            namespace: '{{ namespace }}'
            name: '{{ definition.metadata.name }}'
          vars:
            definition: "{{ lookup('template', '/'.join([deploy_dir, 'operator.yaml.j2'])) | from_yaml }}"
          register: deployment
          until: not deployment.resources
          delay: 3
          retries: 10
          when: delete_deployment.changed

        - name: Create postgres resources
          k8s:
            definition: "{{ lookup('file', deploy_dir + '/../../components/psql/' + item) }}"
            namespace: "{{ namespace }}"
            wait: true
          with_items:
            - 0-secret.yaml
            - 1-pvc.yaml
            - 2-deployment.yaml
            - 3-service.yaml

        - name: Create mq resources
          k8s:
            namespace: "{{ namespace }}"
            definition: "{{ lookup('file', deploy_dir + '/../../components/rabbitmq/' + item) }}"
            wait: true
          with_items:
            - 0-secret.yaml
            - 1-configmap.yaml
            - 2-pvc.yaml
            - 3-service.yaml
            - 4-deployment.yaml

        - name: Create the Operator Deployment
          k8s:
            namespace: '{{ namespace }}'
            definition: "{{ lookup('template', '/'.join([deploy_dir, 'operator.yaml.j2'])) }}"

        - name: Create required custom resources
          k8s:
            state: present
            namespace: '{{ namespace }}'
            definition: '{{ custom_resource }}'

        - name: Wait 5m for reconciliation to run
          k8s_info:
            api_version: '{{ custom_resource.apiVersion }}'
            kind: '{{ custom_resource.kind }}'
            namespace: '{{ namespace }}'
            name: '{{ custom_resource.metadata.name }}'
          register: cr
          until:
            - "'Successful' in (cr | json_query('resources[].status.conditions[].reason'))"
          delay: 10
          retries: 30
      rescue:
        - name: debug cr
          ignore_errors: true
          failed_when: false
          debug:
            var: debug_cr
          vars:
            debug_cr: '{{ lookup("k8s",
              kind=custom_resource.kind,
              api_version=custom_resource.apiVersion,
              namespace=namespace,
              resource_name=custom_resource.metadata.name
            )}}'

        - name: debug po
          ignore_errors: true
          failed_when: false
          k8s_info:
            kind: Pod
            api_version: v1
            namespace: "{{ namespace }}"
          register: debug_po
        - shell: "kubectl logs {{ debug_po.resources[0].metadata.name }} -n {{ namespace }}"
          register: debug_log
        - debug: var=debug_log

        - shell: "kubectl logs `kubectl get pod --selector name=mbox-operator -o jsonpath='{.items[0].metadata.name}'` -n {{ namespace }}"
          register: something
        - debug: var=something

        - command: kubectl get events
          register: log
        - debug: var=log

        - name: get ansible operator logs
          ignore_errors: true
          failed_when: false
          command: kubectl logs `kubectl get pod --selector name=mbox-operator -o jsonpath='{.items[0].metadata.name}'` -n {{ namespace }}
          environment:
            KUBECONFIG: '{{ lookup("env", "KUBECONFIG") }}'
          vars:
            definition: "{{ lookup('template', '/'.join([deploy_dir, 'operator.yaml.j2'])) | from_yaml }}"
          register: log
          
        - debug: var=log.stdout_lines

        - fail:
            msg: "Failed on action: converge"

- import_playbook: '{{ playbook_dir }}/../../default/asserts/koji-hub.yml'
